language: generic
node_js:
  - "node"
python:
  - "3.7"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
  - alias python=python3
  - cd $TRAVIS_BUILD_DIR/scraper && pip3 install -r requirements.txt && npm install
after_success:
  - cd $TRAVIS_BUILD_DIR/scraper && ./scrape-awesome.sh -v 
  - cd $TRAVIS_BUILD_DIR/v4 && firebase deploy --project index-of-knowledge --token $FIREBASE_TOKEN