language: node_js
node_js:
  - "node"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - cd v4 && firebase deploy --project index-of-knowledge --token $FIREBASE_TOKEN